name: Build and deploy on dev


on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes main

env:
  CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            jobs:
              - saagie/jobs/*.json
            pipelines:
              - saagie/pipelines/*.json
              - saagie/pipelines/*.yaml

      - name: Run step if any of the jobs files above change
        if: steps.changed-files-specific.outputs.jobs_any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-specific.outputs.jobs_all_changed_files }}; do
            echo "$file was modified"
            file_name=$(basename ${file})
            file_name_without_ext=${file_name%.*}
            python __main__.py --action package_job --job_name ${file_name_without_ext}
            python __main__.py --action update_job --job_name ${file_name_without_ext} --saagie_url ${{secrets.SAAGIE_URL}} --saagie_user ${{secrets.SAAGIE_USER}} --saagie_pwd ${{secrets.SAAGIE_PWD}} --saagie_realm ${{secrets.SAAGIE_REALM}} --saagie_env dev
          done

      - name: Run step if any of the pipelines files above change
        if: steps.changed-files-specific.outputs.pipelines_any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-specific.outputs.pipelines_all_changed_files }}; do
            echo "$file was modified"
            file_name=$(basename ${file})
            file_name_without_ext=${file_name%.*}
            python __main__.py --action update_pipeline --pipeline_name ${file_name_without_ext} --saagie_url ${{secrets.SAAGIE_URL}} --saagie_user ${{secrets.SAAGIE_USER}} --saagie_pwd ${{secrets.SAAGIE_PWD}} --saagie_realm ${{secrets.SAAGIE_REALM}} --saagie_env dev
          done

      - name: commit and push
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
          git status
          git add .
          git commit -m "[BOT] Add ID in configuration files" && git push || echo "Nothing to commit"